markdown: enhanced_kramdown
pygments: true
lsi: false
safe: false
baseurl: /galaxy

kramdown:
  use_coderay: false

# Site globals used throughout docs.
project: Galaxy
version: 1.3
github: puniverse/galaxy
google_group: "https://groups.google.com/forum/#!forum/galaxy-user"
ga_tracking_id: UA-25007319-2

